### PR TITLE
Added Docker secrets support

### PR DESCRIPTION
**Pull request by silverAndroid**

### CODE REVIEW

**Review by jonathanGB — APPROVED** [review]

**Review by BrandonDanis — CHANGES_REQUESTED** [review]
This PR is for docker secrets, but test.js is being reformatted. Also https://standardjs.com/

**Comment by jonathanGB** [comment]
yep, change to `test.js` should not be part of this PR.

**Comment by BrandonDanis** [comment]
He's trying to sneak semicolons past me 😁

**Review by BrandonDanis — APPROVED** [review]
My name is Brandon Danis, and I approve this PR  😺👍🏽

**Pull request merged**
